### ISSUE TITLE
View Order Page not Opening

### ISSUE THREAD

**Issue by itsjinendrajain** [ShetuRaj/Inventory-Management-and-Billing-Website#1]
This Error is Comming in My terminal.
`Error: ER_WRONG_FIELD_WITH_GROUP: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'itsjinen_warehousedb.ordersdb.TransactionDate' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by 
    at Query.Sequence._packetToError (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Protocol._enqueue (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\mysql\lib\Connection.js:198:25)
    at G:\Testing\Inventory-Management-and-Billing-Website\server.js:200:33
    at Layer.handle [as handle_request] (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\layer.js:95:5)       
    at next (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\route.js:137:13)
    at checkAuthenticated (G:\Testing\Inventory-Management-and-Billing-Website\server.js:173:16)
    at Layer.handle [as handle_request] (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\layer.js:95:5)       
    at next (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (G:\Testing\Inventory-Management-and-Billing-Website\node_modules\express\lib\router\layer.js:95:5) {     
  code: 'ER_WRONG_FIELD_WITH_GROUP',
  errno: 1055,
  sqlMessage: "Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'itsjinen_warehousedb.ordersdb.TransactionDate' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
  sqlState: '42000',
  index: 0,
  sql: 'SELECT TransactionID,SUM(Amount) as Amount,TransactionDate,TransactionTime FROM ordersdb GROUP BY TransactionID'
}`

**Comment by ShetuRaj** [comment]
Have you changed any line in view orders function at line 200 in server.js? And are other pages working?

**Comment by itsjinendrajain** [comment]
i only change this 
`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;` 
to 
`ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`
in sql query.beacuse my Server donot Accept that Type of charset

**Comment by ShetuRaj** [comment]
Can you let me know which version of MySQL are you using and and where did you make the above change (`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`;
to
`ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`)?

**Comment by ShetuRaj** [comment]
Did you try to create columns on your own in the database rather than importing the sql file? It seems like that because the error clearly states that one of the columns has not been defined correctly

**Comment by itsjinendrajain** [comment]
> Can you let me know which version of MySQL are you using and and where did you make the above change (`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`; to `ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`)?

MySQL Version 5.7.36
As this charset is not supported I replace this only , Other are all same .I donot do any change to code.

**Comment by ShetuRaj** [comment]
Can you try upgrading to MySQL version 8.0 as this is the version I had used in the project? It might happen that some features like the one shown in your error might not be there in version 5.7.36

**Comment by ShetuRaj** [comment]
Did your error get resolved? Otherwise I'll be closing this issue?
